#!/usr/bin/python
import smtplib
import base64
import sys
import os

filename = sys.argv[9]
attachedname = filename[filename.rfind("/")+1:]

try:
    fo = open(filename,"rb")
    filecontent = fo.read()
except:
    os.remove(filename);
    sys.quit()

encodedcontent = base64.b64encode(filecontent)

rsfile = sys.argv[10]
rso = open(rsfile,"w")
debugfile = open("/tmp/mail-debug", "w")

FROM = sys.argv[1]
tmp = sys.argv[2]
TO = []
TO = tmp.split(',')
marker = "AUNIQUEMARKER"

body = sys.argv[3]
part1 = """From: %s
To: %s
Subject: %s
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary=%s
--%s
""" % (FROM,tmp, sys.argv[4],marker, marker)

part2="""Content-Type: text/plain
Content-Transfer-Encoding:8bit

%s
--%s
""" % (body,marker)

part3 = """Content-Type: application/pdf; name=\"%s\"
Content-Transfer-Encoding:base64
Content-Disposition: attachment;filename=%s

%s
--%s--
""" % (filename,attachedname,encodedcontent,marker)
message = part1 + part2 + part3
print >> debugfile, message

try:
    server=smtplib.SMTP(sys.argv[5],sys.argv[6])
    server.ehlo()
    server.starttls()
    server.ehlo()
    server.login(sys.argv[7],sys.argv[8])
    smtpresult = server.sendmail(FROM,TO,message)
    if len(smtpresult) > 0:
        print >> rso, smtpresult
    else:
        print >> rso, "0"
    server.quit()
except smtplib.SMTPServerDisconnected:
    print >> rso, "SMTP Server Disconnected"
except smtplib.SMTPAuthenticationError:
    print >> rso, "SMTP Authentication Error"
except smtplib.SMTPResponseException:
    print >> rso, "SMTP Response Exception"
except smtplib.SMTPSenderRefused:
    print >> rso, "SMTP Sender Refused"
except smtplib.SMTPRecipientsRefused:
    print >> rso, "SMTP Recipients Refused Error"
except smtplib.SMTPDataError:
    print >> rso, "SMTP Data Error"
except smtplib.SMTPConnectError:
    print >> rso, "SMTP connect Error"
except smtplib.SMTPHeloError:
    print >> rso, "SMTP Helo Error"
except smtplib.socket.error:
    print >> rso, "General socket error"
except:
    print >> rso, "Exception in sending email"
finally:
    fo.close();
    rso.close();
    os.remove(filename);
