#!/usr/bin/python
import smtplib
import base64
import sys

filename = sys.argv[9]
attachedname = filename[filename.rfind("/")+1:]
fo = open(filename,"rb")
filecontent = fo.read()
encodedcontent = base64.b64encode(filecontent)

FROM = sys.argv[1]
tmp = sys.argv[2]
TO = []
TO = tmp.split(',')
marker = "AUNIQUEMARKER"

body = sys.argv[3]
part1 = """From: %s
To: %s
Subject: %s
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary=%s
--%s
""" % (FROM,tmp, sys.argv[4],marker, marker)

part2="""Content-Type: text/plain
Content-Transfer-Encoding:8bit

%s
--%s
""" % (body,marker)

part3 = """Content-Type: multipart/mixed; name=\"%s\"
Content-Transfer-Encoding:base64
Content-Disposition: attachment;filename=%s

%s
--%s--
""" % (filename,attachedname,encodedcontent,marker)
message = part1 + part2 + part3

server=smtplib.SMTP(sys.argv[5],sys.argv[6])
server.ehlo()
server.starttls()
server.ehlo()
server.login(sys.argv[7],sys.argv[8])
smtpresult = server.sendmail(FROM,TO,message)
print smtpresult
server.quit()

